### ISSUE TITLE
Conflicting metadata name Tactics, need distinguishing prefix

### ISSUE THREAD

**Issue by GalenHare** [joshzelonis/EnterpriseAPT29Eval#4]
Hi there, 
I am getting this error currently. 
Traceback (most recent call last):
  File "EnterpriseAPT29Eval.py", line 302, in <module>
    obj = EnterpriseAPT29Eval(infile)
  File "EnterpriseAPT29Eval.py", line 17, in __init__
    self._df = pd.json_normalize(self._obj,'Steps', ['TechniqueId','TechniqueName', 'Tactics'])
  File "/home/galenhare/.local/lib/python3.8/site-packages/pandas/io/json/_normalize.py", line 354, in _json_normalize
    raise ValueError(
ValueError: Conflicting metadata name Tactics, need distinguishing prefix

Not sure what its about. I am also using linux subsystem for windows if that is any help. Any help would be much appreciated. 
Thank you

**Comment by joshzelonis** [comment]
Thanks, there was a change in the json_normalize call that created this and the fix is having a waterfall effect in the code due to the change in the dataframe, I'm working to fix.

**Comment by joshzelonis** [comment]
I've just pushed an update, sorry for the delay on this.
